version: '3.4'

services:
  rabbitmq:
        container_name: rabbitmq
        ports:
            - 5672:5672
            - 15672:15672
        environment:
            - RABBITMQ_DEFAULT_USER=guest
            - RABBITMQ_DEFAULT_PASS=guest
        image: rabbitmq:3

  devicemicroservice:
    image: ${DOCKER_REGISTRY-}devicemicroservice
    build:
      context: .
      dockerfile: DeviceMicroservice/Dockerfile
    restart: on-failure
    depends_on:
           - rabbitmq

  analyticsmicroservice:
    image: ${DOCKER_REGISTRY-}analyticsmicroservice
    ports:
        - 4000:80
    build:
      context: .
      dockerfile: AnalyticsMicroservice/Dockerfile
    restart: on-failure
    depends_on:
         - mongo
         - rabbitmq

  commandmicroservice:
    image: ${DOCKER_REGISTRY-}commandmicroservice
    build:
      context: .
      dockerfile: CommandMicroservice/Dockerfile
    restart: on-failure
    depends_on:
            - rabbitmq

  gateway:
    image: ${DOCKER_REGISTRY-}gateway
    ports:
        - 5001:80
    build:
      context: .
      dockerfile: Gateway/Dockerfile

  datamicroservice:
    image: ${DOCKER_REGISTRY-}datamicroservice
    build:
      context: .
      dockerfile: data-microservice/Dockerfile
    restart: on-failure
    depends_on:
        - rabbitmq
        - influx

  mongo:
      image: mongo:latest
      container_name: mongo
      ports:
          - 27017:27017
      volumes:
        - mongodata:/data/db

  influx:
      image: influxdb:latest
      container_name: influx
      ports:
          - 8086:8086
      volumes:
        - influxdbdata:/data/db

volumes:
  mongodata:
  influxdbdata:
