version: '3.4'

services:
  rabbitmq:
        container_name: rabbitmq
        ports:
            - 5672:5672
            - 15672:15672
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:15672"]
            interval: 30s
            timeout: 10s
            retries: 5
        environment:
            - RABBITMQ_DEFAULT_USER=guest
            - RABBITMQ_DEFAULT_PASS=guest
        image: rabbitmq:3
  devicemicroservice:
    image: ${DOCKER_REGISTRY-}devicemicroservice
    build:
      context: .
      dockerfile: DeviceMicroservice/Dockerfile
    depends_on:
           - rabbitmq
  analyticsmicroservice:
    image: ${DOCKER_REGISTRY-}analyticsmicroservice
    build:
      context: .
      dockerfile: AnalyticsMicroservice/Dockerfile
    depends_on:
         - mongo    
  commandmicroservice:
    image: ${DOCKER_REGISTRY-}commandmicroservice
    build:
      context: .
      dockerfile: CommandMicroservice/Dockerfile
    depends_on:
            - rabbitmq
  gateway:
    image: ${DOCKER_REGISTRY-}gateway
    ports:
        - 5001:80
    build:
      context: .
      dockerfile: Gateway/Dockerfile
  datamicroservice:
    image: ${DOCKER_REGISTRY-}datamicroservice
    build:
      context: .
      dockerfile: data-microservice/Dockerfile
    restart: on-failure
    depends_on:
        - rabbitmq
        - influx
  mongo:
      image: mongo:latest
      container_name: mongo
      ports:
          - 27017:27017
      volumes:
        - mongodata:/data/db
  influx:
      image: influxdb:latest
      container_name: influx
      ports:
          - 8086:8086
      volumes:
        - influxdbdata:/data/db

volumes:
  mongodata:
  influxdbdata:
