version: '3.4'

services:
  analyticsmicroservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  commandmicroservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"


  devicemicroservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  gateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"