version: '3.4'

services:
  datamicroservice:
    image: ${DOCKER_REGISTRY-}datamicroservice
    build:
      context: .
      dockerfile: DataMicroservice/Dockerfile

  devicemicroservice:
    image: ${DOCKER_REGISTRY-}devicemicroservice
    build:
      context: .
      dockerfile: DeviceMicroservice/Dockerfile

